"""SigMF-compliant metadata (.sigmf-meta) generation and export."""

import json
from pathlib import Path
from typing import Any, Dict
from signalinsight.core.models import AnalysisResult, SignalRecord


class SigMFExporter:
    """Exports signal capture and RF analysis parameters into standard SigMF format."""

    @staticmethod
    def export_metadata(
        signal_rec: SignalRecord,
        output_meta_path: Path,
        analysis_result: Any = None,
    ) -> None:
        output_meta_path = Path(output_meta_path)
        output_meta_path.parent.mkdir(parents=True, exist_ok=True)

        datatype = "cf32_le" if signal_rec.is_complex else "rf32_le"

        meta: Dict[str, Any] = {
            "global": {
                "core:datatype": datatype,
                "core:sample_rate": float(signal_rec.sample_rate),
                "core:version": "1.0.0",
                "core:description": "Generated by SIGNALINSIGHT Professional Signal Analysis",
                "core:author": "SignalInsight Engineering Workstation",
                "core:hw": "Software Defined Radio / Digitizer",
            },
            "captures": [
                {
                    "core:sample_start": 0,
                    "core:frequency": float(signal_rec.center_frequency),
                    "core:datetime": signal_rec.timestamp.isoformat() + "Z",
                }
            ],
            "annotations": [],
        }

        # If analysis results exist, add modulation classification as an annotation
        if analysis_result and hasattr(analysis_result, "modulation_result") and analysis_result.modulation_result:
            mod_res = analysis_result.modulation_result
            meta["annotations"].append(
                {
                    "core:sample_start": 0,
                    "core:sample_count": signal_rec.sample_count,
                    "core:label": f"Modulation: {mod_res.predicted_modulation}",
                    "signalinsight:confidence": float(mod_res.confidence),
                    "signalinsight:probabilities": mod_res.class_probabilities,
                }
            )

        with open(output_meta_path, "w", encoding="utf-8") as f:
            json.dump(meta, f, indent=2)
